## Part 1: Conceptual Check (15 min)

Test your understanding before diving into the code.

**Question 1:** What is the key difference between a Pandas `Series` and a `DataFrame`?\
A Series is a one-dimensional array with labeled indices. It's the building block of a DataFrame.\
A DataFrame is a 2-dimensional labeled data structure. Think of it as a dictionary of Series objects (each column is a Series).

**Question 2:** You run `df.loc[0:3]`. How many rows do you get? What about `df.iloc[0:3]`?\
.loc[row_label, col_label]: "Address" based.\
.iloc[row_pos, col_pos]: "GPS" based (integers).

**Question 3:** You have a DataFrame with a `price` column stored as `object` type (strings like "£45.99"). What problem does this cause, and how do you fix it?\
It will run into these three major issues: Mathematical Failure, Incorrect Sorting, and Memory Inefficiency.\
To fix this:
1. Remove the currency symbol and any commas
2. Convert the column to a float\
df['price'] = df['price'].str.replace('£', '', regex=False).str.replace(',', '', regex=False).astype(float)

**Question 4:** When would you use `.apply()` instead of a direct vectorised operation like `df['col'] * 2`?
| Feature | Vectorized (`df * 2`) | `.apply()` |
| :--- | :--- | :--- |
| **Speed** | **Extremely Fast** (C-based) | **Slower** (Python-based loop) |
| **Complexity** | Best for simple math/logic | Best for "messy" or custom logic |
| **Readability** | High for standard operations | High for complex business rules |
| **Memory** | Efficient | Can be intensive |

**Question 5:** How do you select all numeric columns from a DataFrame, excluding float types?
```python
# Selects all numbers (int and float), then drops the floats
numeric_minus_floats = df.select_dtypes(include='number', exclude='float')

# Selects only integer types (int64, int32, etc.)
integer_columns = df.select_dtypes(include='integer')
```

### Challenge 1: Build and Inspect the Dataset

Create the following DataFrame and perform a health check:

```python
import pandas as pd

books = pd.DataFrame({
    'title': ['The Pragmatic Programmer', 'Clean Code', 'Python Crash Course',
              'Data Science from Scratch', 'Designing Data-Intensive Apps'],
    'author': ['Hunt & Thomas', 'Robert Martin', 'Eric Matthes',
               'Joel Grus', 'Martin Kleppmann'],
    'genre': ['Tech', 'Tech', 'Tech', 'Data', 'Data'],
    'price': [45.99, 38.50, 29.99, 42.00, 55.00],
    'units_sold': [120, 95, 200, 80, 60],
    'in_stock': [True, True, False, True, False]
})
```

**Tasks:**
1. Use `.info()` — how many non-null values does each column have?
2. Use `.describe()` — what's the average price and maximum units sold?
3. Add a `revenue` column: `price × units_sold`.
4. What is the total revenue across all books?

In [17]:
import pandas as pd
import numpy as np

books = pd.DataFrame({
    'title': ['The Pragmatic Programmer', 'Clean Code', 'Python Crash Course',
              'Data Science from Scratch', 'Designing Data-Intensive Apps'],
    'author': ['Hunt & Thomas', 'Robert Martin', 'Eric Matthes',
               'Joel Grus', 'Martin Kleppmann'],
    'genre': ['Tech', 'Tech', 'Tech', 'Data', 'Data'],
    'price': [45.99, 38.50, 29.99, 42.00, 55.00],
    'units_sold': [120, 95, 200, 80, 60],
    'in_stock': [True, True, False, True, False]
})
display(books)

print("1. Use `.info()` — how many non-null values does each column have?")
books.info()
print()

print("2. Use `.describe()` — what's the average price and maximum units sold?")
books.describe()
print(books.describe())
print()

print("3. Add a `revenue` column: `price × units_sold`.")
books['revenue'] = books['price'] * books['units_sold']
display(books)
print()

print("4. What is the total revenue across all books?")
total_revenue = books['revenue'].sum()
print(f"Total Revenue: ${total_revenue:,.2f}")
print()

,title,author,genre,price,units_sold,in_stock
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,120,True
1,Clean Code,Robert Martin,Tech,38.50,95,True
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True
4,Designing Data-Intensive Apps,Martin Kleppmann,Data,55.00,60,False

1. Use `.info()` — how many non-null values does each column have?
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       5 non-null      object
 1   author      5 non-null      object
 2   genre       5 non-null      object
 3   price       5 non-null      float64
 4   units_sold  5 non-null      int64
 5   in_stock    5 non-null      bool
dtypes: bool(1), float64(1), int64(1), object(3)
memory usage: 333.0+ bytes

2. Use `.describe()` — what's the average price and maximum units sold?
           price  units_sold
count   5.000000    5.000000
mean   42.296000  111.000000
std     9.232715   54.359912
min    29.990000   60.000000
25%    38.500000   80.000000
50%    42.000000   95.000000
75%    45.990000  120.000000
max    55.000000  200.000000

3. Add a `revenue` column: `price × units_sold`.

,title,author,genre,price,units_sold,in_stock,revenue
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,120,True,5518.8
1,Clean Code,Robert Martin,Tech,38.50,95,True,3657.5
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False,5998.0
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True,3360.0
4,Designing Data-Intensive Apps,Martin Kleppmann,Data,55.00,60,False,3300.0

4. What is the total revenue across all books?
Total Revenue: $21,834.30

### Challenge 2: Indexing & Filtering

**Tasks:**
1. Use `.loc` to select only `title` and `revenue` for Data genre books.
2. Use `.iloc` to retrieve the last 3 rows and first 3 columns.
3. Filter books that are **in stock** AND have a **price above £40**.
4. Find the book with the **highest revenue** using `.loc` with `.idxmax()`.

In [24]:
display(books)

print("1. Use `.loc` to select only `title` and `revenue` for Data genre books.")
data_books = books.loc[books['genre'] == 'Data', ['title', 'revenue']]
display(data_books)

print("2. Use `.iloc` to retrieve the last 3 rows and first 3 columns.")
last_3_rows_first_3_columns = books.iloc[-3:,:3]
display(last_3_rows_first_3_columns)

print("3. Filter books that are **in stock** AND have a **price above £40**.")
in_stock_expensive = books.loc[(books['in_stock'] == True) & (books['price'] > 40)]
display(in_stock_expensive)

print("4. Find the book with the **highest revenue** using `.loc` with `.idxmax()`.")
highest_revenue_book = books.loc[books['revenue'].idxmax()]
display(highest_revenue_book)

,title,author,genre,price,units_sold,in_stock,revenue
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,120,True,5518.8
1,Clean Code,Robert Martin,Tech,38.50,95,True,3657.5
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False,5998.0
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True,3360.0
4,Designing Data-Intensive Apps,Martin Kleppmann,Data,55.00,60,False,3300.0

1. Use `.loc` to select only `title` and `revenue` for Data genre books.

                           title  revenue
3      Data Science from Scratch   3360.0
4  Designing Data-Intensive Apps   3300.0

2. Use `.iloc` to retrieve the last 3 rows and first 3 columns.

                           title            author genre
2            Python Crash Course      Eric Matthes  Tech
3      Data Science from Scratch         Joel Grus  Data
4  Designing Data-Intensive Apps  Martin Kleppmann  Data

3. Filter books that are **in stock** AND have a **price above £40**.

,title,author,genre,price,units_sold,in_stock,revenue
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,120,True,5518.8
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True,3360.0

4. Find the book with the **highest revenue** using `.loc` with `.idxmax()`.

title         Python Crash Course
author               Eric Matthes
genre                        Tech
price                       29.99
units_sold                    200
in_stock                    False
revenue                    5998.0
Name: 2, dtype: object

### Challenge 3: Transform, Sort & Rank

**Tasks:**
1. Use `.apply()` to add a `price_tier` column: `'Budget'` (< £35), `'Standard'` (£35–£50), `'Premium'` (> £50).
2. Sort the DataFrame by `revenue` descending.
3. Add a `sales_rank` column using `.rank(ascending=False)`.
4. Use `.map()` to encode `genre` as a number: `{'Tech': 0, 'Data': 1}`.

In [26]:
display(books)

print("1. Use `.apply()` to add a `price_tier` column: `'Budget'` (< £35), `'Standard'` (£35–£50), `'Premium'` (> £50).")
def price_tier(price):
    if price < 35:
        return 'Budget'
    elif 35 <= price <= 50:
        return 'Standard'
    else:
        return 'Premium'
books['price_tier'] = books['price'].apply(price_tier)
display(books)  

print("2. Sort the DataFrame by `revenue` descending.")
books_sorted = books.sort_values(by='revenue', ascending=False)
display(books_sorted)

print("3. Add a `sales_rank` column using `.rank(ascending=False)`.")
books['sales_rank'] = books['units_sold'].rank(ascending=False).astype(int)
display(books)

print("4. Use `.map()` to encode `genre` as a number: `{'Tech': 0, 'Data': 1}`.")
books['genre_encoded'] = books['genre'].map({'Tech': 0, 'Data': 1})
display(books)

,title,author,genre,price,units_sold,in_stock,revenue,price_tier
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,120,True,5518.8,Standard
1,Clean Code,Robert Martin,Tech,38.50,95,True,3657.5,Standard
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False,5998.0,Budget
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True,3360.0,Standard
4,Designing Data-Intensive Apps,Martin Kleppmann,Data,55.00,60,False,3300.0,Premium

1. Use `.apply()` to add a `price_tier` column: `'Budget'` (< £35), `'Standard'` (£35–£50), `'Premium'` (> £50).

,title,author,genre,price,units_sold,in_stock,revenue,price_tier
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,120,True,5518.8,Standard
1,Clean Code,Robert Martin,Tech,38.50,95,True,3657.5,Standard
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False,5998.0,Budget
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True,3360.0,Standard
4,Designing Data-Intensive Apps,Martin Kleppmann,Data,55.00,60,False,3300.0,Premium

2. Sort the DataFrame by `revenue` descending.

,title,author,genre,price,units_sold,in_stock,revenue,price_tier
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False,5998.0,Budget
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,120,True,5518.8,Standard
1,Clean Code,Robert Martin,Tech,38.50,95,True,3657.5,Standard
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True,3360.0,Standard
4,Designing Data-Intensive Apps,Martin Kleppmann,Data,55.00,60,False,3300.0,Premium

3. Add a `sales_rank` column using `.rank(ascending=False)`.

,title,author,genre,price,units_sold,in_stock,revenue,price_tier,sales_rank
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,120,True,5518.8,Standard,2
1,Clean Code,Robert Martin,Tech,38.50,95,True,3657.5,Standard,3
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False,5998.0,Budget,1
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True,3360.0,Standard,4
4,Designing Data-Intensive Apps,Martin Kleppmann,Data,55.00,60,False,3300.0,Premium,5

4. Use `.map()` to encode `genre` as a number: `{'Tech': 0, 'Data': 1}`.

,title,author,genre,price,units_sold,in_stock,revenue,price_tier,sales_rank,genre_encoded
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,120,True,5518.8,Standard,2,0
1,Clean Code,Robert Martin,Tech,38.50,95,True,3657.5,Standard,3,0
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False,5998.0,Budget,1,0
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True,3360.0,Standard,4,1
4,Designing Data-Intensive Apps,Martin Kleppmann,Data,55.00,60,False,3300.0,Premium,5,1

Stretch Challenge (Optional)

The manager wants a report comparing average price and total revenue by `price_tier`. Use `groupby()` to generate this summary. Which tier contributes the most total revenue despite having the lowest average price?

In [ ]:
report = books.groupby('price_tier').agg({'price': 'mean', 'revenue': 'sum'}).reset_index()
report.rename(columns={'price': 'average_price', 'revenue': 'total_revenue'}, inplace=True)
display(report)

  price_tier  average_price  total_revenue
0     Budget      29.990000         5998.0
1    Premium      55.000000         3300.0
2   Standard      42.163333        12536.3